name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vim:
        - v8.2.1000
        - v8.2.0000
        - v8.1.0000
        - v8.0.0000
        - v7.4
        - v7.3
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Checkout vim-themis
      uses: actions/checkout@master
      with:
        repository: thinca/vim-themis
        path: vim-themis
    - name: Setup Vim
      uses: rhysd/action-setup-vim@v1
      id: vim
      with:
        version: ${{ matrix.vim }}
    - name: Test
      env:
        THEMIS_VIM: ${{ steps.vim.outputs.executable }}
      run: ./vim-themis/bin/themis --reporter spec
